#!/usr/bin/env zsh

# Ensure stow is installed...
installed=$(type stow | grep "not found")

if [ -z $installed ]; then
  # Find all directories starting with an '@' symbol. Those are our stow packages.
  ls | awk '{print $1}' | grep "@[a-zA-Z0-9]*" | while read dir; do
    echo "Unstow'ing '$dir'."
    stow -D $dir -t $HOME
  done
else
  echo "GNU stow not found. Please install stow: https://www.gnu.org/software/stow/"
  exit 1
fi
