# CATPUCCIN for TMUX BREAKING CHANGES
# Setup basics
set -g default-terminal "tmux-256color"
set -g mouse on

# Plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#latest' # See https://github.com/catppuccin/tmux/tags for additional tags

# Catpuccin
set -g @catppuccin_flavor 'mocha' # latte,frappe, macchiato or moch:
set -g @catppuccin_window_status_style "rounded"

run ~/.config/tmux/plugins/tmux/catppuccin.tmux

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# Terminal hyperlink support w/mouse (click SHIFT)
set -ga terminal-features "*:hyperlinks"

# Set prefix binding
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Bind r so we can resource configuration
unbind r 
bind r source-file ~/.config/tmux/tmux.conf

# Window splitting
bind | split-window -h
bind - split-window -v

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'
run '~/.config/tmux/plugins/tpm/tpm'
