# UI Colors (extended)
accent = "#2895A3"
cursor = "#9F9F84"

# Primary colors
foreground = "#9F9F84"
background = "#01070a"

# Selection colors
selection_foreground = "#01070a"
selection_background = "#9F9F84"

# Normal colors (ANSI 0-7)
color0 = "#01070a"
color1 = "#a96d2f"
color2 = "#5d7f63"
color3 = "#87804e"
color4 = "#2895A3"
color5 = "#966f4c"
color6 = "#368B8D"
color7 = "#9F9F84"

# Bright colors (ANSI 8-15)
color8 = "#636a6d"
color9 = "#d4903d"
color10 = "#7da580"
color11 = "#aca663"
color12 = "#48bcce"
color13 = "#be9364"
color14 = "#54b2b4"
color15 = "#c5c6a2"
