# Background and foreground colors
background = #01070a
foreground = #9F9F84

# Standard colors
palette = 0=#01070a
palette = 1=#a96d2f
palette = 2=#5d7f63
palette = 3=#87804e
palette = 4=#2895A3
palette = 5=#966f4c
palette = 6=#368B8D
palette = 7=#9F9F84

# Bright colors
palette = 8=#636a6d
palette = 9=#d4903d
palette = 10=#7da580
palette = 11=#aca663
palette = 12=#48bcce
palette = 13=#be9364
palette = 14=#54b2b4
palette = 15=#c5c6a2
