$color = rgba(1, 7, 10, 1)
$inner_color = rgba(1, 7, 10, 0.66)
$outer_color = rgba(150, 111, 76, 1)
$font_color = rgba(159, 159, 132, 1)
$placeholder_color = rgba(159, 159, 132, 0.7)
$check_color = rgba(54, 139, 141, 1)
