background            #01070a
foreground            #9F9F84

# black
color0  #01070a
color8  #636a6d

# red
color1  #a96d2f
color9  #d4903d

# green
color2  #5d7f63
color10 #7da580

# yellow
color3  #87804e
color11 #aca663

# blue
color4  #2895A3
color12 #48bcce

# magenta
color5  #966f4c
color13 #be9364

#cyan
color6  #368B8D
color14 #54b2b4

#white
color7  #9F9F84
color15 #c5c6a2


