# COLORS
BACKGROUND=default      # transparent
FOREGROUND=colour244    # subtle 'gray'
ACTIVE=white            # match current theme
OS_ICON=cyan            # match current theme
MESSAGE_BG=default
MESSAGE_FG=green


# DEFAULT STYLES
set -g status-style fg=$FOREGROUND,bg=$BACKGROUND
set -Fg 'status-format[1]' '#{status-format[0]}'
set -g 'status-format[0]' ''
set -g status 2
set -g status-position-bottom

# iNACTIVE WINDOWS
set -g window-status-format "#[fg=$FOREGROUND] #I:#W"

# ACTIVE WINDOW
set -g window-status-current-format "#[fg=$ACTIVE] \uf192 #I:#W"

# STATUS LINE OPTIONS
set -g status-right-length 50
set -g status-left-length 50
set -g status-left "#[fg=$OS_ICON]#(~/.config/tmux/os-icon.sh)  "
set -ga status-left "#[fg=$FOREGROUND]#[window_index]"
set -g status-right " user: #{client_user}@#{host} "
set -ga status-right " session: #{?#{==:#{session_name},#{session_id}},#{session_index},#{session_name}}"

# General messages
set -g message-style "fg=$MESSAGE_FG bg=$MESSAGE_BG,bold"

# Command prompt (Prefix + :)
set -g message-command-style "fg=$MESSAGE_FG,bg=$MESSAGE_BG,bold"

