
[window]

opacity = 0.85
padding.x = 10
padding.y = 10
blur = true
dimensions = { columns = 115, lines = 30 }
decorations = "Full"
decorations_theme_variant = "Dark" 

[font]

normal.family = "FiraCode Nerd Font Mono"
bold.family = "FiraCode Nerd Font Mono"
italic.family = "FiraCode Nerd Font Mono"
bold_italic.family = "FiraCode Nerd Font Mono"
size = 16.0

[env]
TERM = "xterm-256color"

[general]
# All config options available at 
# https://github.com/tmcdonell/config-alacritty/blob/master/alacritty.yml

import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]
