
-- Generated by nwg-displays on 2026-06-08 at 10:40:30. Do not edit manually.

local is_docked = #hl.get_monitors()

if (is_docked) then
  hl.workspace_rule({
      workspace = "1",
      monitor = "DP-1",
      default = true
  })
  hl.workspace_rule({
      workspace = "2",
      monitor = "DP-1"
  })
  hl.workspace_rule({
      workspace = "3",
      monitor = "DP-1"
  })
  hl.workspace_rule({
      workspace = "4",
      monitor = "DP-1"
  })
  hl.workspace_rule({
      workspace = "5",
      monitor = "DP-1"
  })
  hl.workspace_rule({
      workspace = "6",
      monitor = "DP-1"
  })
  hl.workspace_rule({
      workspace = "7",
      monitor = "DP-1"
  })
    hl.workspace_rule({
      workspace = "8",
      monitor = "DP-1"
  })
  hl.workspace_rule({
    workspace = "9",
    monitor = "DP-2"
  })
  hl.workspace_rule({
    workspace = "10",
    monitor = "DP-2"
  })
end
