#   _   __                                 _     
#  | | / /                                | |    
#  | |/ /  ___ _   ___      _____  _ __ __| |___ 
#  |    \ / _ \ | | \ \ /\ / / _ \| '__/ _` / __|
#  | |\  \  __/ |_| |\ V  V / (_) | | | (_| \__ \
#  \_| \_/\___|\__, | \_/\_/ \___/|_|  \__,_|___/
#               __/ |                            
#              |___/                             
#                                                
# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty -e tmux
$fileManager = thunar 
$menu = wofi --show drun
$browser = brave-browser
