# ___  ___            _ _                 
# |  \/  |           (_) |                
# | .  . | ___  _ __  _| |_ ___  _ __ ___ 
# | |\/| |/ _ \| '_ \| | __/ _ \| '__/ __|
# | |  | | (_) | | | | | || (_) | |  \__ \
# \_|  |_/\___/|_| |_|_|\__\___/|_|  |___/
                                          
# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,auto
monitor = DP-1, 2560x1080, 2560x0, 1
monitor = HDMI-A-1, 2560x1440, 0x0, 1

# Workspace -> Monitor rules
workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-1
workspace = 9, monitor:DP-1
workspace = 10, monitor:HDMI-A-1
