#  ___  ___            _ _                 
#  |  \/  |           (_) |                
#  | .  . | ___  _ __  _| |_ ___  _ __ ___ 
#  | |\/| |/ _ \| '_ \| | __/ _ \| '__/ __|
#  | |  | | (_) | | | | | || (_) | |  \__ \
#  \_|  |_/\___/|_| |_|_|\__\___/|_|  |___/
                                          
# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=,preferred,auto,auto
monitor = DP-1, 2560x1080, 2560x0, 1
monitor = HDMI-A-1, 2560x1440, 0x0, 1
